[package]
name = "kernel"
version = "0.1.0"
authors = ["hj"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
volatile-register = "0.2.0"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"