# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/seungwoo/Downloads/qos2/qos.srcs/sources_1/bd/design_1/ip/design_1_fifo_copro_0_1/design_1_fifo_copro_0_1.xci
# IP: The module: 'design_1_fifo_copro_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/seungwoo/Downloads/qos2/qos.srcs/sources_1/bd/design_1/ip/design_1_fifo_copro_0_1/src/fifo_generator_0_1/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: /home/seungwoo/Downloads/qos2/qos.srcs/sources_1/bd/design_1/ip/design_1_fifo_copro_0_1/src/fifo_generator_0_1/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home/seungwoo/Downloads/qos2/qos.srcs/sources_1/bd/design_1/ip/design_1_fifo_copro_0_1/design_1_fifo_copro_0_1.xci
# IP: The module: 'design_1_fifo_copro_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/seungwoo/Downloads/qos2/qos.srcs/sources_1/bd/design_1/ip/design_1_fifo_copro_0_1/src/fifo_generator_0_1/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: /home/seungwoo/Downloads/qos2/qos.srcs/sources_1/bd/design_1/ip/design_1_fifo_copro_0_1/src/fifo_generator_0_1/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
